"""add gallery_photos table

Revision ID: 11951e0ca43d
Revises: 486ff8056cca
Create Date: 2026-07-26 23:38:53.100572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11951e0ca43d'
down_revision: Union[str, Sequence[str], None] = '486ff8056cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gallery_photos')
    # ### end Alembic commands ###
