"""add stripe_invoice_id to donations

Revision ID: 420d9c558af6
Revises: a5c3d07718c5
Create Date: 2026-07-26 23:58:46.623471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420d9c558af6'
down_revision: Union[str, Sequence[str], None] = 'a5c3d07718c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_donations_stripe_invoice_id'), 'donations', ['stripe_invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_stripe_invoice_id'), table_name='donations')
    op.drop_column('donations', 'stripe_invoice_id')
    # ### end Alembic commands ###
