"""add hero_slides table

Revision ID: 486ff8056cca
Revises: 3bc20a69b6c4
Create Date: 2026-07-26 22:03:00.944127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '486ff8056cca'
down_revision: Union[str, Sequence[str], None] = '3bc20a69b6c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero_slides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('badge_text', sa.String(length=120), nullable=False),
    sa.Column('cta_label', sa.String(length=60), nullable=False),
    sa.Column('cta_href', sa.String(length=255), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hero_slides')
    # ### end Alembic commands ###
