"""extend donations for embedded checkout

Revision ID: 693190c7f9e1
Revises: 420d9c558af6
Create Date: 2026-07-27 00:42:43.029885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693190c7f9e1'
down_revision: Union[str, Sequence[str], None] = '420d9c558af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('donor_phone', sa.String(length=50), nullable=True))
    op.add_column('donations', sa.Column('dedication', sa.String(length=255), nullable=True))
    op.add_column('donations', sa.Column('billing_details', sa.JSON(), nullable=True))
    op.add_column('donations', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_donations_stripe_payment_intent_id'), 'donations', ['stripe_payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_stripe_payment_intent_id'), table_name='donations')
    op.drop_column('donations', 'stripe_customer_id')
    op.drop_column('donations', 'billing_details')
    op.drop_column('donations', 'dedication')
    op.drop_column('donations', 'donor_phone')
    # ### end Alembic commands ###
