"""add donations table

Revision ID: a5c3d07718c5
Revises: 11951e0ca43d
Create Date: 2026-07-26 23:55:43.110858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c3d07718c5'
down_revision: Union[str, Sequence[str], None] = '11951e0ca43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('donor_user_id', sa.Uuid(), nullable=True),
    sa.Column('donor_name', sa.String(length=255), nullable=False),
    sa.Column('donor_email', sa.String(length=255), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.Enum('one_time', 'monthly', name='donation_frequency', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', name='donation_status', native_enum=False), nullable=False),
    sa.Column('is_fee', sa.Boolean(), nullable=False),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['donor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_campaign_id'), 'donations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_donations_donor_email'), 'donations', ['donor_email'], unique=False)
    op.create_index(op.f('ix_donations_stripe_checkout_session_id'), 'donations', ['stripe_checkout_session_id'], unique=False)
    op.create_index(op.f('ix_donations_stripe_subscription_id'), 'donations', ['stripe_subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donations_stripe_subscription_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_stripe_checkout_session_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_donor_email'), table_name='donations')
    op.drop_index(op.f('ix_donations_campaign_id'), table_name='donations')
    op.drop_table('donations')
    # ### end Alembic commands ###
